# List behaviour:
# - blacklist: AntiXRay will only be applied to worlds that ARE NOT in the list.
# - whitelist: AntiXRay will only be applied to worlds that ARE in the list.
mode: "blacklist"
# List names of worlds here.
worlds: []

# How far fake ores should be reverted to their real blocks from an updated block.
revert-radius: 2